function displayPoem(response) {
  console.log("poem generated");
  new Typewriter("#poem", {
    strings: response.data.answer,
    autoStart: true,
    delay: 50,
    cursor: "",
  });
}

function generatePoem(event) {
  event.preventDefault();

  let instructionsInput = document.querySelector("#user-instructions");
  if (!instructionsInput) {
    console.error("Element with ID 'user-instructions' not found.");
    return;
  }

  let instructionsInput = document.querySelector("#user-instructions");
  let apiKey = "c9b0ec623aacc60coeb8df5a545t1489";
  let prompt = `Generate a Dutch Poem about ${instructionsInput.value}`;
  let context =
    "User instructions are: You are a romantic Poem expert and love to write short poems. Your mission is to generate a 4 line poem in basic HTML and separate each line with <br> Sign the poem with generated by ShecodesAI. Make sure to follow the user instructions. Do not include a title in the Poem";
  let apiURL = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  console.log("Generating poem");
  console.log(`prompt: ${prompt}`);
  console.log(`context: ${context}`);

  axios
    .get(apiURL)
    .then(displayPoem)
    .catch((error) => {
      console.error("Error fetching poem:", error);
      // Handle the error appropriately
    }); // Ends Axios request
} // Ends generatePoem function

document.addEventListener("DOMContentLoaded", function () {
  let poemFormElement = document.querySelector("#poem-generator-form");
  poemFormElement.addEventListener("submit", generatePoem);
});
